Bug: Order properties should not be accessed directly
shipit-team/shipit-wordpress pull request #36
Opened 2020-12-18 03:49 UTC by multinauta

I changed the way to get the  order properties, using getters. I also added a log to store the response from the server when shipments are created.

2020-12-18 12:28 UTC, Zeaneth commented on shipit/trunk/readme.txt
> +*Agregamos un log para guardar la respues del servicio al crear el envío.
`respues`

2020-12-18 12:28 UTC, Zeaneth commented on shipit/trunk/src/shipit_debug.php
> +        $current_date = date('d/m/Y H:i:s');
Is there a reason for not using camel case for `current_date` variable as well?

2020-12-18 12:45 UTC, multinauta commented on shipit/trunk/src/shipit_debug.php
> +        $current_date = date('d/m/Y H:i:s');
nopes,  i will change it

2020-12-18 13:42 UTC, mnanom approved these changes

2020-12-18 19:40 UTC, luispascuali approved these changes

2020-12-18 20:12 UTC, Zeaneth reviewed
What about `bulk_actions.php` file? Shouldn't this also be calling order with the getters?

2020-12-28 13:06 UTC, hiro-riveros requested changes

2020-12-28 13:06 UTC, hiro-riveros commented on shipit/trunk/shipit.php
> +      $r = json_decode(json_encode($request), true);
The variable `$r` mean?

2020-12-28 13:06 UTC, hiro-riveros commented on shipit/trunk/src/shipit_debug.php
> +    {
curly braces at the same line of the `debug` function definition.

2020-12-28 13:50 UTC, multinauta commented on shipit/trunk/shipit.php
> +      $r = json_decode(json_encode($request), true);
request to array , i will change it

2020-12-28 13:50 UTC, multinauta commented on shipit/trunk/src/shipit_debug.php
> +    {
i will change it

2020-12-29 13:36 UTC, hiro-riveros approved these changes

2020-12-29 14:06 UTC, merged