[WIP] TECH-1252 Feature: add README documentation
shipit-team/shipit-wordpress pull request #41
Opened 2021-06-16 23:17 UTC by multinauta

Refer: https://app.clickup.com/t/3077149/TECH-1252

Why I'm adding these lines of code?

- to document installation and use

2021-06-16 23:17 UTC, hiro-riveros commented
Task linked: [TECH-1252 Documentar Shipit-Wordpress](https://app.clickup.com/t/3077149/TECH-1252)

2021-06-17 23:52 UTC, Zeaneth requested changes

2021-06-17 23:52 UTC, Zeaneth commented on README.md
> +The following project is a plugin for wordpress which interacts with the woocommerce plugin to be able to generate pricing, import sales and update order statuses. To testing in local we must install
```suggestion
The following project is a plugin for WordPress that interacts with the WooCommerce plugin to generate pricing, import sales, and update order statuses. To test in local, we must install a WordPress instance.
```

2021-06-17 23:52 UTC, Zeaneth commented on README.md
> +| Technology | Versión |
```suggestion
| Technology | Version |
```

2021-06-17 23:52 UTC, Zeaneth commented on README.md
> +| Woocommerce | Last |
```suggestion
| WooCommerce | Last |
```

2021-06-17 23:57 UTC, multinauta commented on README.md
> +The following project is a plugin for wordpress which interacts with the woocommerce plugin to be able to generate pricing, import sales and update order statuses. To testing in local we must install
Thanks!

2021-06-18 00:07 UTC, Zeaneth reviewed
I hadn't seen the other two 😅

2021-06-18 00:07 UTC, Zeaneth commented on README.md
> +## Others products necesary
```suggestion
## Others necessary products
```

2021-06-18 00:07 UTC, Zeaneth commented on README.md
> +## Requeriments
```suggestion
## Requirements
```

2021-06-18 00:20 UTC, multinauta commented on README.md
> +## Others products necesary
Done!

2021-06-18 15:01 UTC, Zeaneth approved these changes

2021-06-18 15:04 UTC, luispascuali approved these changes

2021-06-18 15:34 UTC, gcamposm approved these changes

2021-06-18 16:04 UTC, David25848 approved these changes

2021-06-23 00:28 UTC, Barbycris approved these changes

2021-06-23 00:31 UTC, mgraterol approved these changes

2021-06-30 19:45 UTC, HaNdlezz approved these changes

2021-07-01 20:41 UTC, merged