Refer: #4x9t1y Bug: sent correctly the time of the creation of the or…
shipit-team/shipit-wordpress pull request #43
Opened 2021-06-29 22:27 UTC by davidmaring7

## Refer: 

-Task: https://app.clickup.com/t/4x9t1y

## Why I'm adding these lines of code?

- Because we need to correctly send the order creation time in the seller's store for the suite display.

## Before

![image](https://user-images.githubusercontent.com/43593752/123875054-06fa5680-d907-11eb-9c97-bd926ce15f0f.png)

## After

![Captura de pantalla de 2021-06-29 18-24-18](https://user-images.githubusercontent.com/43593752/123875219-46c13e00-d907-11eb-96e4-08c6bed0b309.png)

2021-06-29 22:48 UTC, Zeaneth requested changes

2021-06-29 22:48 UTC, Zeaneth commented on shipit/tags/3.3.2/readme.txt
> +Version: 3.3.1
```suggestion
Stable tag: 3.3.2
Version: 3.3.2
```

2021-06-29 22:48 UTC, Zeaneth commented on shipit/trunk/readme.txt
> += 3.3.2 =
Update stable version on lines 8 and 9

2021-06-30 14:03 UTC, davidmaring7 commented on shipit/trunk/readme.txt
> += 3.3.2 =
Done. @Zeaneth :+1:

2021-06-30 15:02 UTC, multinauta commented
on line 5 of shipit.php update the version

2021-06-30 21:42 UTC, multinauta approved these changes

2021-06-30 21:47 UTC, tostitos-dev requested changes
Include message to the "nuevasfuncionalidades" channel

2021-07-01 15:40 UTC, gcamposm approved these changes

2021-07-01 18:26 UTC, Barbycris approved these changes
You never assign yourself to the PR 🤔

2021-07-01 20:17 UTC, luispascuali approved these changes

2021-07-01 22:21 UTC, tostitos-dev approved these changes

2021-07-01 22:23 UTC, Zeaneth reviewed
the branch's name is not up to our standards (with an underscore `_` instead of `-`).

2021-07-01 22:24 UTC, Zeaneth approved these changes

2021-07-01 22:25 UTC, merged