Reference:#1gb36z3, Improvement: Adding Same day to woocommerce
shipit-team/shipit-wordpress pull request #51
Opened 2021-09-14 17:46 UTC by davidmaring7

# Reference

- Task [#1gb36z3](https://app.clickup.com/t/1gb36z3)

# Why I'm adding these lines of code

- To add same day to woocommerce

# Message to the "nuevasfuncionalidades" channel

- (Mejora) [#1gb36z3](https://app.clickup.com/t/1gb36z3) Adaptar plugin woocommerce para recibir estructura SDD

2021-09-14 18:03 UTC, gcamposm commented on shipit/trunk/readme.txt
> +* Agrega la funcionalidad para aceptar envios con entrega el mismo dia.
```suggestion
* Agrega la funcionalidad para aceptar envíos con entrega el mismo día.
```

2021-09-14 18:03 UTC, gcamposm commented on shipit/trunk/readme.txt
> +* Arregla problema de creacion de envios en accion masiva
Maybe 'Corrige/Repara'
```suggestion
* Arregla problema de creación de envíos en acción masiva
```

2021-09-14 18:03 UTC, gcamposm commented on shipit/trunk/src/shipit_service/rate.php
> +    function getRateDescription($checkout, $drescription, $woocommerceSetting) {
```suggestion
    function getRateDescription($checkout, $description, $woocommerceSetting) {
```

2021-09-14 18:05 UTC, multinauta requested changes
- in the tag folder, it must not be compressed
- in the test section you could place the checkout image working

2021-09-14 18:05 UTC, multinauta commented on shipit/trunk/readme.txt
> +* Arregla problema de creacion de envios en accion masiva
```suggestion
* Arregla problema de creación de envíos en acción masiva
```

2021-09-14 18:05 UTC, multinauta commented on shipit/trunk/src/shipit_service/rate.php
> +    function getRateDescription($checkout, $drescription, $woocommerceSetting) {
```suggestion
    function getRateDescription($checkout, $description, $woocommerceSetting) {
```

2021-09-14 19:34 UTC, davidmaring7 commented on shipit/trunk/readme.txt
> +* Agrega la funcionalidad para aceptar envios con entrega el mismo dia.
Done, thanks @gcamposm

2021-09-14 19:35 UTC, davidmaring7 commented on shipit/trunk/readme.txt
> +* Arregla problema de creacion de envios en accion masiva
Done @multinauta thanks👍🏻

2021-09-14 20:36 UTC, gcamposm approved these changes

2021-09-14 20:36 UTC, gcamposm commented on shipit/trunk/readme.txt
> +* Arregla problema de creación de envíos en acción masiva
Maybe "Corrige" / "Repara"

2021-09-14 20:53 UTC, anyelopetit approved these changes

2021-09-15 00:28 UTC, multinauta approved these changes

2021-09-23 19:25 UTC, HaNdlezz approved these changes

2021-09-23 22:49 UTC, hiro-riveros approved these changes

2021-09-23 22:49 UTC, merged